### ISSUE TITLE
Higher Resolution?

### ISSUE THREAD

**Issue by Turlan** [universome/epigraf#4]
Thanks for the great work! I am wondering whether you have tried to increase the image resolution to 1024x1024?

**Comment by universome** [comment]
Hi @Turlan, thank you! To be honest, we tried launching the training on 1024x1024 once on FFHQ, but it gave us slightly worse results (FID ~15), and we didn't investigate it further since then due to the time constraints and because the majority of the methods were investigating 256x256 or 512x512 generation which we wanted to compare to

**Comment by Turlan** [comment]
Thanks for your kindly reply.
