### ISSUE TITLE
Custom FFHQ Training

### ISSUE THREAD

**Issue by zhukaii** [universome/epigraf#9]
When the custom ffhq dataset is adopted without camera pose information, the error exists in train.py (line 127, "Broken yaw angles (all zeros)"). So how can I reproduce the ffhq training result similar to the one in paper?

**Comment by universome** [comment]
Hi! Camera conditioning is a crucial ingredient to learn decent geometry for FFHQ since it contains too many frontal images and the learnt geometry will be flat otherwise. So, I do not think that it is possible to reproduce the results without using camera poses from GRAM (which you can download from [their repo](https://github.com/microsoft/GRAM)).
